import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  Check, 
  X, 
  ArrowRight,
  Filter
} from 'lucide-react';
import { useInvestigation } from '../context/InvestigationContext';
import { AlertItem } from '../types';

export const AlertsPage: React.FC = () => {
  const navigate = useNavigate();
  const { alerts, setCurrentScenarioId, setSelectedCaseId } = useInvestigation();
  const [alertList, setAlertList] = useState<AlertItem[]>(alerts);
  const [filterSeverity, setFilterSeverity] = useState('all');
  const [filterStatus, setFilterStatus] = useState('all');

  const handleDismiss = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setAlertList(prev => prev.map(a => a.id === id ? { ...a, status: 'Dismissed' } : a));
  };

  const handleAssign = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setAlertList(prev => prev.map(a => a.id === id ? { ...a, status: 'Assigned' } : a));
  };

  const handleInvestigate = (alert: AlertItem) => {
    setCurrentScenarioId(alert.scenarioType);
    if (alert.caseId) {
      setSelectedCaseId(alert.caseId);
      navigate(`/investigations/${alert.caseId}`);
    } else {
      navigate('/investigations');
    }
  };

  const filtered = alertList.filter(a => {
    if (filterSeverity !== 'all' && a.severity !== filterSeverity) return false;
    if (filterStatus !== 'all' && a.status !== filterStatus) return false;
    return true;
  });

  return (
    <div className="p-8 space-y-6 max-w-7xl mx-auto select-none">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-border pb-4">
        <div>
          <h1 className="text-2xl font-bold text-text-primary tracking-tight">
            Compliance Alerts
          </h1>
          <p className="text-sm text-text-secondary mt-1">
            Incoming surveillance alerts generated by multi-bank pattern detection triggers.
          </p>
        </div>

        {/* Filter Controls */}
        <div className="flex items-center gap-2 text-xs">
          <select
            value={filterSeverity}
            onChange={(e) => setFilterSeverity(e.target.value)}
            className="bg-white border border-border text-text-secondary rounded px-3 py-1.5 focus:outline-none focus:border-brand"
          >
            <option value="all">All risk levels</option>
            <option value="critical">High / Critical</option>
            <option value="high">Medium-High</option>
            <option value="warning">Warning / Low</option>
          </select>

          <select
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value)}
            className="bg-white border border-border text-text-secondary rounded px-3 py-1.5 focus:outline-none focus:border-brand"
          >
            <option value="all">All statuses</option>
            <option value="New">Open</option>
            <option value="Under Investigation">Investigating</option>
            <option value="Assigned">Assigned</option>
            <option value="Dismissed">Resolved / Dismissed</option>
          </select>
        </div>
      </div>

      {/* Conventional Compliance Inbox Table */}
      <div className="bg-white rounded-card border border-border shadow-card overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-surface-secondary border-b border-border text-[11px] font-semibold text-text-muted uppercase">
              <tr>
                <th className="py-3 px-4">Alert</th>
                <th className="py-3 px-4">Pattern</th>
                <th className="py-3 px-4">Account</th>
                <th className="py-3 px-4 font-mono-numbers">Amount</th>
                <th className="py-3 px-4">Institution</th>
                <th className="py-3 px-4">Risk</th>
                <th className="py-3 px-4">Created</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {filtered.map((alert) => (
                <tr
                  key={alert.id}
                  onClick={() => handleInvestigate(alert)}
                  className="hover:bg-surface-hover cursor-pointer transition-colors"
                >
                  <td className="py-3 px-4 font-mono font-semibold text-brand whitespace-nowrap">
                    {alert.id}
                  </td>

                  <td className="py-3 px-4 font-medium text-text-primary whitespace-nowrap">
                    {alert.pattern}
                  </td>

                  <td className="py-3 px-4 font-mono text-text-secondary whitespace-nowrap">
                    {alert.involvedAccounts[0]} ({alert.accountsCount} total)
                  </td>

                  <td className="py-3 px-4 font-mono-numbers font-semibold text-text-primary whitespace-nowrap">
                    ₹{(alert.amount / 100000).toFixed(2)}L
                  </td>

                  <td className="py-3 px-4 text-text-secondary whitespace-nowrap">
                    {alert.institution}
                  </td>

                  <td className="py-3 px-4 whitespace-nowrap">
                    <span className={`px-2 py-0.5 rounded text-[11px] font-medium border ${
                      alert.severity === 'critical'
                        ? 'bg-risk-subtle text-risk border-risk-border'
                        : 'bg-warning-subtle text-warning border-warning-border'
                    }`}>
                      {alert.severity === 'critical' ? 'High' : 'Medium'}
                    </span>
                  </td>

                  <td className="py-3 px-4 text-text-muted whitespace-nowrap">
                    {alert.timestamp.split(' ')[1]}
                  </td>

                  <td className="py-3 px-4 whitespace-nowrap">
                    <span className="text-text-secondary">
                      {alert.status === 'New' ? 'Open' : alert.status}
                    </span>
                  </td>

                  <td className="py-3 px-4 text-right whitespace-nowrap" onClick={(e) => e.stopPropagation()}>
                    <div className="flex items-center justify-end gap-2">
                      <button
                        onClick={() => handleInvestigate(alert)}
                        className="text-brand font-medium hover:underline text-xs"
                      >
                        Investigate
                      </button>
                      <span className="text-text-muted">|</span>
                      <button
                        onClick={(e) => handleDismiss(alert.id, e)}
                        className="text-text-muted hover:text-text-primary text-xs"
                      >
                        Dismiss
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
